import type { Metadata } from "next";
import { Libre_Caslon_Display } from "next/font/google";
import "./globals.css";
import PrelineScript from "./PrelineScript";
import { Providers } from "./providers";
import { Provider } from "./provida";

const libreCaslon = Libre_Caslon_Display({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={libreCaslon.className}>
        <Provider>
          <Providers>{children}</Providers>
          <PrelineScript />
        </Provider>
      </body>
    </html>
  );
}
